/** TanStack Query keys — scoped by userId to prevent cross-account cache bleed. */
export const queryKeys = {
    dashboard: (userId, period, startDate, endDate) => [
        'dashboard',
        userId,
        period,
        startDate ?? null,
        endDate ?? null,
    ],
    businessInfo: (userId) => ['businessInfo', userId],
    businessAssets: (userId) => ['businessAssets', userId],
    invoiceUsage: (userId) => ['invoiceUsage', userId],
    invoiceMeta: (userId) => ['invoiceMeta', userId],
    invoices: (userId, params) => ['invoices', userId, params],
    quotations: (userId, params) => ['quotations', userId, params],
    clients: (userId, params) => ['clients', userId, params],
    products: (userId, params) => ['products', userId, params],
    drafts: (userId, params) => ['drafts', userId, params],
    receipts: (userId, params) => ['receipts', userId, params],
    suppliers: (userId, params) => ['suppliers', userId, params],
    purchaseOrders: (userId, params) => ['purchaseOrders', userId, params],
    inventoryStock: (userId, params) => ['inventoryStock', userId, params],
    inventoryMovements: (userId, params) => ['inventoryMovements', userId, params],
    inventorySummary: (userId) => ['inventorySummary', userId],
    listSummary: (userId, resource, summaryYear, summaryMonth) => [
        'listSummary',
        userId,
        resource,
        summaryYear,
        summaryMonth,
    ],
    adminUsers: (userId, params) => ['adminUsers', userId, params],
    profit: (userId, period, startDate, endDate) => [
        'profit',
        userId,
        period,
        startDate ?? null,
        endDate ?? null,
    ],
    expenses: (userId, params) => ['expenses', userId, params],
    expenseSummary: (userId, period, startDate, endDate) => [
        'expenseSummary',
        userId,
        period,
        startDate ?? null,
        endDate ?? null,
    ],
};

export const STALE_TIMES = {
    dashboard: 30_000,
    lists: 2 * 60_000,
    listSummary: 5 * 60_000,
    businessInfo: 5 * 60_000,
    meta: 60_000,
};
