export {
    extractDocumentSequence,
    receiptFromInvoiceNumber,
    PAYMENT_METHODS,
    MARK_PAID_METHODS,
    isReceipt,
    getPaymentMethodLabel,
    getReceiptNumber,
    getDisplayNumber,
    getDocumentNumber,
    getDocumentTypeLabel,
    getPdfFileName,
    getDownloadLabel,
    resolvePdfMode,
    INV_PREFIX,
    RCP_PREFIX,
    QTN_PREFIX,
} from '@waraqah/shared';
